---
title: "PP Model Code"
format: html
editor: visual
---

```{r}
library(rstan)
library(bayesplot)
```

```{r}
source("cleaning.R")

sector_panel <- cumu_returns %>%
  select(date, sector_name, cum_log_return)

market_series <- cumu_returns_sp500 %>%
  select(date, market_cum_log_return = cum_log_return)

model_data_long <- sector_panel %>%
  inner_join(market_series, by = "date") %>%
  arrange(sector_name, date)

model_data_long %>%
  count(sector_name)
```

```{r}
y_wide <- model_data_long %>%
  select(date, sector_name, cum_log_return) %>%
  pivot_wider(names_from = date, values_from = cum_log_return) %>%
  arrange(sector_name)

sector_names <- y_wide$sector_name
y_mat <- y_wide %>%
  select(-sector_name) %>%
  as.matrix()

m_vec <- model_data_long %>%
  distinct(date, market_cum_log_return) %>%
  arrange(date) %>%
  pull(market_cum_log_return)

```


# run the model
```{r}
# finding gamma priors
all_y <- as.vector(y_mat)

mean_y <- mean(all_y, na.rm = TRUE)
sd_y   <- sd(all_y, na.rm = TRUE)
var_y  <- var(all_y, na.rm = TRUE)
mean_prec <- 1 / var_y
sd_prec   <- mean_prec / 2 
a_tau <- (mean_prec / sd_prec)^2
b_tau <- mean_prec / (sd_prec^2)

stan_data <- list(
  N = nrow(y_mat),
  T = ncol(y_mat),
  y = y_mat,
  m = m_vec,
  a_tau = a_tau,
  b_tau = b_tau, 
  alpha_mu = 0,
  alpha_sd = 0.7,
  phi_transform_mu = 2,
  phi_transform_sd = 0.4,
  beta_transform_mu = 2.5,
  beta_transform_sd = 0.4
)

fit <- stan(
  file = "pp_model_4_23.stan",
  data = stan_data,
  chains = 4,
  iter = 2000,
  seed = 123,
  control = list(adapt_delta = 0.95, max_treedepth = 12)
)

```

```{r}
# this gives results for each sector
print(fit, pars = c("phi", "beta"), probs = c(0.025, 0.5, 0.975))

traceplot(fit, pars = "phi")
traceplot(fit, pars = "beta")

stan_ac(fit, pars = "phi")
stan_ac(fit, pars = "beta")
```


# Posterior predictive checks
```{r}
post <- rstan::extract(fit)

y_rep_array <- post$y_rep

y_obs <- as.vector(y_mat)
y_rep_mat <- apply(y_rep_array, 1, function(x) as.vector(x))
y_rep_mat <- t(y_rep_mat)

ppc_dens_overlay(y_obs, y_rep_mat[1:50, ]) +
  theme_classic()

sector_ids <- rep(1:nrow(y_mat), each = ncol(y_mat))

ppc_dens_overlay_grouped(y = y_obs, yrep = y_rep_mat[1:50, ], group = sector_ids) +
  theme_classic()

ppc_intervals(
  y_obs,
  yrep = y_rep_mat[1:50, ],
  prob = 0.5,
  prob_outer = 0.95
) +
  theme_classic()
```

# forecast
```{r}
# most recent observed sector cumulative returns
last_y <- y_mat[, ncol(y_mat)]

# most recent observed market cumulative return
last_m <- m_vec[length(m_vec)]

stan_data_pred <- list(
  N = nrow(y_mat),
  T = ncol(y_mat),
  y = y_mat,
  m = m_vec,
  a_tau = a_tau,
  b_tau = b_tau, 
  alpha_mu = 0,
  alpha_sd = 0.7,
  phi_transform_mu = 2,
  phi_transform_sd = 0.4,
  beta_transform_mu = 2.5,
  beta_transform_sd = 0.4,
  N_new = nrow(y_mat),
  sector_new = 1:nrow(y_mat),
  y_lag_new = last_y,
  m_lag_new = rep(last_m, nrow(y_mat))
)

fit_pred <- stan(
  file = "pp_prediction.stan",
  data = stan_data_pred,
  chains = 4,
  iter = 2000,
  seed = 123,
  control = list(adapt_delta = 0.95, max_treedepth = 12)
)

post_pred <- rstan::extract(fit_pred, pars = "y_pred_new")[[1]]

pred_summary <- data.frame(
  sector = sector_names,
  pred_mean = apply(post_pred, 2, mean),
  lower_95 = apply(post_pred, 2, quantile, 0.025),
  upper_95 = apply(post_pred, 2, quantile, 0.975)
)

pred_summary

library(ggplot2)

ggplot(pred_summary, aes(x = sector, y = pred_mean)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower_95, ymax = upper_95), width = 0.2) +
  theme_classic() +
  labs(
    title = "One-week-ahead posterior predictions by sector",
    x = "Sector",
    y = "Predicted cumulative log return"
  ) +
  coord_flip()
```

